### ISSUE TITLE
excessive number of messages

### ISSUE THREAD

**Issue by bakman2** [scraton/node-red-contrib-plex-ws#1]
Any flow advice how use this to turn on light on pause and dim on play ?
Currently every second it spits out 5 messages which I don't want to sent to my lights directly. Even a rate limit of 1 per 10 seconds would be too often. 

Better would be to have a state node that only tracks changes; stopped,playing,paused.

**Comment by scraton** [comment]
Hi there!

Which node are you attempting to use? The [playing node](https://github.com/scraton/node-red-contrib-plex-ws#playing) should cover the use case you described. If that's what you're using and you're still getting that many messages let me know. That would be unusual behavior.

**Comment by bakman2** [comment]
That's what I hoped for ;) 
node-red log show errors coming from the node:
```
(node:11552) UnhandledPromiseRejectionWarning: undefined
(node:11552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by scraton** [comment]
I finally got around to digging into this, but I can't seem to replicate the problem. Even without any filters, I'm only getting a single message out for each status change.

Do you have "Allow Updates" checked? If so, try unchecking that. That option is the only thing I can think that would be causing duplicate status messages.

If you've already got that unchecked, can you share a flow demonstrating the problem? Can you also let me know the Plex Media Server version you're using?

**Comment by bakman2** [comment]
Hmm I created a new flow to test and now I can't reproduce it either.  Still get the error `UnhandledPromiseRejectionWarning: undefined` when playing, but only one payload is received. 

When allow updates is checked I do get more messages but not as many I had before. Strange.
