### ISSUE TITLE
Plex TLS errors

### ISSUE THREAD

**Issue by bakman2** [scraton/node-red-contrib-plex-ws#7]
I recently updated the plex app on my synology and now get this continuously:
```
plex error: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 10.0.0.200 is not in the cert's list: "
```
and it no longer connects to Plex. Disabling TLS stops the messages, but it doesn't connect to Plex.

**Comment by scraton** [comment]
I’m not familiar with using TLS with Plex, but I’ll do my best to help.

When you created the certificate, did you add that IP to the list of valid addresses? I believe you need to specifically specify the IP for the cert as well as the hostname for it to be valid. You may also need to install the CA or the self signed cert itself on the machine running Node RED.

Does changing the secure option in the node’s settings panel have any effect?
