### ISSUE TITLE
playing node throws error

### ISSUE THREAD

**Issue by andrasg** [scraton/node-red-contrib-plex-ws#8]
The notification node works fine, but the playing node throws the following error on all play events:

`"failed to fetch session details from plex: Error: read ECONNRESET"`

Looks like it's not able to retrieve the session details for some reason.

**Comment by scraton** [comment]
This may have been fixed with https://github.com/scraton/node-red-contrib-plex-ws/issues/3. Please update to 0.2.4 and if you're still experiencing the issue, feel free to re-open the issue. :)
